
pipelines: 
  - name: state_test_git
    steps:
      - name: step-one
        type: Bash
        configuration:
        execution:
          onExecute:
            - echo "executing step-one"
      
      - name: step-two
        type: Bash
        configuration:
          inputSteps:
            - name: step-one
        execution:
          onExecute:
            - echo "executing step-two"
