
pipelines: 
  - name: state_test_git
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: git
        execution:
          onExecute:
            - pushd $res_git_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
            - sleep 2
            - echo 'https://github.com/shiptest-bt/ymlTest/edit/master/pipelines.yml'
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
