
pipelines: 
  - name: state_test_git
    steps:
      - name: step_one
        type: Bash
        execution:
          onExecute:
            - echo "executing step_one"
      
      - name: step_two
        type: Bash
        configuration:
          inputSteps:
            - name: step_one
        execution:
          onExecute:
            - echo "executing step_two"
