
pipelines: 
  - name: test_pip
    steps:
      - name: step_one
        type: Bash
        execution:
          onExecute:
            - echo "executing step_one"
      
      - name: step_two
        type: Bash
        configuration:
          inputSteps:
            - name: step_one
        execution:
          onExecute:
            - echo "executing step_two"
  - name: demo
    steps:
      - name: checkEntplusApi
        type: HealthCheck
        syntaxVersion: 0.0.1
        configuration:
          healthCheckUrl: "https://entplus.jfrog.io/artifactory/api/system/ping"
          #showTimeTaken: true
          #showOuptut: true
          #retry: 3
